### ISSUE TITLE
C# Quickstart Requires Some Nuget Packages

### ISSUE THREAD

**Issue by jdetter** [clockworklabs/spacetime-docs#4]
The C# quickstart guide requires:
 - Newtonsoft.Json
 - Google.Protobuf

This is completely undocumented and if you don't add these nuget packages the quickstart guide ends in a bunch of errors

**Comment by RReverser** [comment]
@cloutiertyler I don't know which quickstart this is referring to. C# modules don't rely on those packages, so I'm assuming this is for client SDK. If so, @jdetter was probably the right assignee.

**Comment by RReverser** [comment]
Closing as C# clients no longer require to declare those dependencies.
